# Generated by Django 3.2.9 on 2021-11-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211114_1732'),
        ('product', '0003_auto_20211111_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.sellerprofile'),
            preserve_default=False,
        ),
    ]
