# Generated by Django 3.2.9 on 2022-01-01 22:08

import django.core.validators
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, validators=[product.models.validate_gte_null]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, validators=[product.models.validate_gte_null, django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_quantity',
            field=models.IntegerField(default=0, validators=[product.models.validate_gte_null]),
        ),
    ]
