# Generated by Django 3.2.9 on 2022-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_unique_user_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_product',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_purchase_user_product'),
        ),
    ]
