# Generated by Django 3.2.9 on 2021-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.FloatField(default=0, max_length=256),
        ),
    ]
