# Generated by Django 3.2.9 on 2021-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211114_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('SELLER', 'seller')], default='USER', max_length=9),
        ),
    ]
