# Generated by Django 3.2.9 on 2021-11-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_confirm',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
